### ISSUE TITLE
Try first install got error

### ISSUE THREAD

**Issue by Iquaridys** [getherbie/herbie#137] opened 2023-06-20 08:51 UTC
I try install with composer and got Unknown "css_add" function.
how to fix it?

**Comment by tbreuss** [comment] 2023-06-20 09:49
@Iquaridys Which command exactly did you execute? Can you give some additional hints?

I suspect there is a version conflict somewhere. I will try to reproduce and fix the error.

**Comment by tbreuss** [comment] 2023-06-20 12:55
@Iquaridys The twig function `css_add` is delivered with the system plugin called `twig`, see <https://github.com/getherbie/herbie/tree/2.x/plugins/twig>.

The twig plugin is shipped with the code but is disabled by default. To enable it, add twig to the `enabledSysPlugins` configuration option.

~~~php
return [
    'enabledSysPlugins' => 'twig'
];
~~~ 

I will make this more clear within the documentation.

You can see a configuration example at <https://github.com/getherbie/start-website/blob/master/site/config/main.php>.

**Comment by Iquaridys** [comment] 2023-06-21 13:44
> @Iquaridys The twig function `css_add` is delivered with the system plugin called `twig`, see https://github.com/getherbie/herbie/tree/2.x/plugins/twig.
> 
> The twig plugin is shipped with the code but is disabled by default. To enable it, add twig to the `enabledSysPlugins` configuration option.
> 
> ```
> return [
>     'enabledSysPlugins' => 'twig'
> ];
> ```
> 
> I will make this more clear within the documentation.
> 
> You can see a configuration example at https://github.com/getherbie/start-website/blob/master/site/config/main.php.

i try use laragon and try with php -S  but still got error

**Comment by tbreuss** [comment] 2023-06-21 17:28
@Iquaridys Can you describe what you did exactly and in which environment? That would be very helpful to reproduce the error.

**Comment by tbreuss** [comment] 2023-07-08 10:01
Closing this problem, since not reproducible

**Closed as completed by tbreuss** 2023-07-08 10:01 UTC
